[deps]
CompositionalNetworks = "4b67e4b5-442d-4ef5-b760-3f5df3a57537"
ConstraintDomains = "5800fd60-8556-4464-8d61-84ebf7a0bedb"
Constraints = "30f324ab-b02d-43f0-b619-e131c61659f7"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LocalSearchSolvers = "2b10edaa-728d-4283-ac71-07e312d6ccf3"
